# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-05 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=None, max_length=63)),
                ('desc', models.CharField(blank=None, max_length=255)),
                ('imgUrl', models.ImageField(blank=None, upload_to='projects/images')),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
