# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-05 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(blank=None, max_length=70),
        ),
    ]
