# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-22 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200605_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.CharField(blank=None, default='APP', max_length=70),
        ),
    ]
